version: 0.2

phases:
  deploy:
    commands:
      - mu database upsert production src/resources/db/mysql/schema.sql
      - mu database upsert production src/resources/db/mysql/data.sql
artifacts:
  files:
    - '**/*'